version: '2'

services:
  etcd:
    image: registry.cn-beijing.aliyuncs.com/k7scn/etcd:3-debian-10
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
volumes:
  etcd_data:
    driver: local
